#!/usr/bin/env node

var http = require("http");

var options = {
    host: 'www.doviz.tv',
    port: 80,
    path: '/altinjson/'
};

http.get(options, function(res) {
    var data = "";
    if (res.statusCode !== 200) {
        console.log("Error: got response: " + res.statusCode);
        return;
    }
    res.setEncoding('utf8');
    res.on('data', function (chunk) {
        data += chunk;
    });
    res.on('end', function () {
        data = JSON.parse(data.slice(1));
        var tarih = data.yil + "/" + data.ay + "/" + data.gun;
        console.log(tarih + " tarihinde 22 Ayar Altin;" +
                    " Alis: " + data.Y22Al + " TL, Satis: " + data.Y22Sat + " TL.");
    });
}).on('error', function(e) {
    console.log("Got error: " + e.message);
});

// vim: set filetype=javascript :
