#!/bin/bash

# this scripts sets up an ssh tunnel from localhost:PORT to REMOTE:PORT

source ~/bin/common.sh

SERVER=$1
PORT=5432

if [ $# -lt 1 ]; then
	warn "usage: sshprx server [port]"
	warn "  port defaults to 5432"
	exit 1
fi

if [ $# -gt 1 ]; then
	PORT=$2
fi

inf "* Mapping $SERVER:$PORT to localhost:$PORT"
inf "* Type ctrl-c to stop"
ssh -N $SERVER -L $PORT:localhost:$PORT

# vim: set filetype=sh :

