#!/bin/bash

# this scripts sets up an ssh tunnel from localhost:PORT to REMOTE:PORT
# remote can be an ip address or a hostname

source ~/bin/common.sh

SERVER=$1
PORT=5432

if [ $# -lt 1 ]; then
	warn "usage: sshprx server [port]"
	warn "  server can be an ip address or hostname"
	warn "  port defaults to $PORT"
	warn "  common ports:"
	warn "    5432  POSTGRES"
	warn "    3389  REMOTE DESKTOP"
	exit 1
fi

if [ $# -gt 1 ]; then
	PORT=$2
fi

if [ ! "$(echo $SERVER | grep '[0-9]\{1,3\}[.][0-9]\{1,3\}[.][0-9]\{1,3\}[.][0-9]\{1,3\}')" ]
then
	DESTINATION=`dig +short A $SERVER`
	inf "* Resolved $SERVER as $DESTINATION"
else
	DESTINATION=$SERVER
fi
inf "* Mapping $DESTINATION:$PORT to localhost:$PORT"
inf "* Type ctrl-c to stop"
ssh -N $DESTINATION -L $PORT:localhost:$PORT

# vim: set filetype=sh :

